/** Generates a personalised SKILL.md for a Travel Pal user's imported agent. */
export function generateSkillMd(params: {
  nickname: string
  walletAddress: string
  countryCode: string
  city: string
  country: string
}): string {
  const { nickname, walletAddress, countryCode, city, country } = params
  return `# Travel Pal Agent Skill

## About This Skill
This skill teaches your Personal Agent (PA) how to operate inside Travel Pal on behalf of **${nickname}**.

## User Context
| Field | Value |
|---|---|
| Nickname | ${nickname} |
| Agent Wallet | \`${walletAddress}\` |
| Current Location | ${city}, ${country} (${countryCode}) |
| Network | Arc Testnet |
| Token | USDC (6 decimals, ERC-20) |

## Guardrails (Strict — Never Override)
1. **Never sign or broadcast a transaction** without an explicit, text-based confirmation from ${nickname} in the current session.
2. **Never share or log the wallet private key or passkey credential.** These are device-bound.
3. **Never transfer more than ${nickname} explicitly states** — always echo the exact amount and destination before acting.
4. **Only interact with verified contract addresses** from the \`@/onchain-facts\` module. Reject any address not in that registry unless ${nickname} explicitly overrides after reading a security warning.
5. **Offramp flows must confirm the fiat currency and amount** before initiating. Display the detected local fiat from the geolocation engine.

## How to Find Relevant Notifications
Travel Pal's geo-fenced feed is keyed to the user's detected country code (\`${countryCode}\`).
- **Security alerts** — advisories from national travel safety bodies for ${country}.
- **Cultural tips** — etiquette, hidden gems, local customs relevant to ${city}.
- **Transport** — local transit options, fare tips, and app recommendations.
- **Health** — emergency numbers, food safety, and medical access for ${country}.

To surface the most relevant notification, filter the feed by:
1. Category matching the user's current intent (e.g. "getting around" → transport).
2. Unread status — prioritise items the user has not yet dismissed.
3. Recency — prefer alerts timestamped within the last 6 hours.

## Available App Actions
| Action | How to Invoke |
|---|---|
| Check USDC balance | Read from the balance card (polls every 5 seconds automatically) |
| Deposit USDC | Tap "Deposit" → copy wallet address or scan QR |
| Convert to local fiat | Tap "Cash Out" → Onramper widget pre-fills ${countryCode} currency |
| View/dismiss alerts | Feed panel → filter by All or Unread |
| Change background | Tap camera icon → upload travel photos or toggle geo mode |

## Continuation Protocol
When resuming a session via Import PA:
1. Verify the wallet address matches \`${walletAddress}\`.
2. Re-read the feed panel for any new unread alerts since the last session.
3. Check the USDC balance — if below a threshold set by ${nickname}, prompt a deposit reminder.
4. Greet ${nickname} by name and summarise the top unread alert for their current location.

---
*Generated by Travel Pal · ${new Date().toISOString().split('T')[0]}*
`
}
